# initializes the latex log subsystem 
initialize_log = function(output = "latex-include", name = "r-exports") {
    system(paste0("mkdir -p ", output))
    LATEX_LOG_FOLDER <<- output
    if (! exists("LATEX_LOGS")) {
        LATEX_LOGS <<- list()
    }
    if (! name %in% LATEX_LOGS)
        LATEX_LOGS[[name]] <<- list()
    LATEX_CURRENT_LOG <<- name
    cat(paste0("Latex log folder: ", output, "\n"))
    cat(paste0("Available latex logs:", length(LATEX_LOGS), "\n"))
    cat(paste0("Current latex log: ", LATEX_CURRENT_LOG, " (", length(LATEX_LOGS[[LATEX_CURRENT_LOG]]), " entries)\n"))
}

flush_log = function(name = LATEX_CURRENT_LOG) {
    logFile = paste0(LATEX_LOG_FOLDER, "/", name, ".sty")
    cat(paste0("Flushing log ", name, " to file ", logFile, "\n"))
    write_line = function(...) {
        line = paste0(...)
        write(line, file = logFile, append = T)
        cat(paste0(line, "\n"))
    }
    write("%autogenerated contents", file = logFile)
    for (key in names(LATEX_LOGS[[name]])) {
        x = LATEX_LOGS[[name]][[key]]
        if (is.numeric(x))
            x = format(round(x, 2), nsmall=0, big.mark=",", scientific = F)
        write_line("\\newcommand{\\", key, "}{", x, "\\xspace}")
    }
}

LOG = function(key, value, logName = LATEX_CURRENT_LOG) {
    if (! logName %in% names(LATEX_LOGS)) {
        cat(paste0("!!! Latex log ", logName, " does not exist. Creating.\n"))
        LATEX_LOGS[[logName]] <<- list()
    }
    LATEX_LOGS[[logName]][[key]] <<- value
    cat(paste0("[", logName,"]: ", key, " : ", value, "\n"))
}

LOGPct = function(key, value, total, logName = LATEX_CURRENT_LOG) {
    LOG(key, value, logName)
    LOG(paste0(key,"Pct"), paste0(round(value / total, 2) * 100, "\\%"))
}